org_id = "456692188473"
billing_account = "ddgdg"
default-region = "northamerica-northeast1"
terraform_service_account = "org-terraform@cantech-terraform.iam.gserviceaccount.com"
project_id = "cantech-terraform"
admin_service_account = "admin"